package com.hisense.serverestimate.mapper;

import com.hisense.serverestimate.entity.ErrorExamDetail;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ErrorExamDetailMapper {

    int addErrorExamDetail(@Param("errorMsg") String errorMsg, @Param("examResult")String examResult);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_exam_detail
     *
     * @mbggenerated Thu Jul 11 18:39:30 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_exam_detail
     *
     * @mbggenerated Thu Jul 11 18:39:30 CST 2019
     */
    int insert(ErrorExamDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_exam_detail
     *
     * @mbggenerated Thu Jul 11 18:39:30 CST 2019
     */
    ErrorExamDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_exam_detail
     *
     * @mbggenerated Thu Jul 11 18:39:30 CST 2019
     */
    List<ErrorExamDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_exam_detail
     *
     * @mbggenerated Thu Jul 11 18:39:30 CST 2019
     */
    int updateByPrimaryKey(ErrorExamDetail record);
}