package com.hisense.serverestimate.entity;

import java.io.Serializable;

public class ErrorExamDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_exam_detail.id
     *
     * @mbggenerated Thu Jul 11 18:39:30 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_exam_detail.error_msg
     *
     * @mbggenerated Thu Jul 11 18:39:30 CST 2019
     */
    private String errorMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_exam_detail.exam_result
     *
     * @mbggenerated Thu Jul 11 18:39:30 CST 2019
     */
    private String examResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table error_exam_detail
     *
     * @mbggenerated Thu Jul 11 18:39:30 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_exam_detail.id
     *
     * @return the value of error_exam_detail.id
     *
     * @mbggenerated Thu Jul 11 18:39:30 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_exam_detail.id
     *
     * @param id the value for error_exam_detail.id
     *
     * @mbggenerated Thu Jul 11 18:39:30 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_exam_detail.error_msg
     *
     * @return the value of error_exam_detail.error_msg
     *
     * @mbggenerated Thu Jul 11 18:39:30 CST 2019
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_exam_detail.error_msg
     *
     * @param errorMsg the value for error_exam_detail.error_msg
     *
     * @mbggenerated Thu Jul 11 18:39:30 CST 2019
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_exam_detail.exam_result
     *
     * @return the value of error_exam_detail.exam_result
     *
     * @mbggenerated Thu Jul 11 18:39:30 CST 2019
     */
    public String getExamResult() {
        return examResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_exam_detail.exam_result
     *
     * @param examResult the value for error_exam_detail.exam_result
     *
     * @mbggenerated Thu Jul 11 18:39:30 CST 2019
     */
    public void setExamResult(String examResult) {
        this.examResult = examResult == null ? null : examResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_exam_detail
     *
     * @mbggenerated Thu Jul 11 18:39:30 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", errorMsg=").append(errorMsg);
        sb.append(", examResult=").append(examResult);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}